### ISSUE TITLE
A good lib for SSE

### ISSUE THREAD

**Issue by icantunderstand** [Bewinxed/river.ts#1]
i have read the source code. i think the design of steam function in server is a good pattern. it use callback to connect each other.

**Comment by Bewinxed** [comment]
> i have read the source code. i think the design of steam function in server is a good pattern. it use callback to connect each other.

Thank you for the kind comment 😄 let me know if you have any suggestion.

ありがとう ございます

**Comment by Bewinxed** [comment]
♥
![XecDtfDF_400x400](https://github.com/Bewinxed/river.ts/assets/9145989/2e33a42d-3e18-41eb-a6b2-28a3d256ba12)
